### ISSUE TITLE
DGPv2: missing `dokkaGenerateHtml` and `dokkaGenerateJavadoc` lifecycle tasks

### ISSUE THREAD

**Issue by adam-enko** [orangy/dokka#3960]
The DGPv2 migration docs reference tasks that don't exist

https://github.com/Kotlin/dokka/blob/fc574c855fb75a4fe30185aa9f12b74295b095d4/docs/topics/dokka-migration.md?plain=1#L405

The tasks should exist, and the tasks names are defined [here](https://github.com/Kotlin/dokka/blob/v2.0.0/dokka-runners/dokka-gradle-plugin/src/main/kotlin/tasks/TaskNames.kt#L14), but for some unknown reason they are not registered as tasks (mistake while copying Dokkatoo? Or during another PR? Or were they intentionally removed?).

### Tasks

- [ ] Find out what tasks should be used instead of `dokkaGenerateHtml` and `dokkaGenerateJavadoc`. (Probably `dokkaGeneratePublicationHtml`?)
- [ ] The docs should be updated to remove the references. Instead replace them with the above.
- [ ] Investigate and determine if the tasks should be re-added. (I'm on the fence. I think it's confusing if there's too many tasks, but on the other hand `dokkaGeneratePublicationHtml` is a mouthful, and there's no obvious difference between it and `dokkaGenerateModuleHtml`, so a shorter lifecycle helper task could help.)
